# Generated by Django 5.1 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="sentiment",
            field=models.CharField(
                choices=[
                    ("calm", "Calm"),
                    ("neutral", "Neutral"),
                    ("frustrated", "Frustrated"),
                    ("angry", "Angry"),
                ],
                default="neutral",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="urgency_score",
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sentiment__in", ["calm", "neutral", "frustrated", "angry"])
                ),
                name="ticket_sentiment_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.CheckConstraint(
                condition=models.Q(("urgency_score__gte", 0), ("urgency_score__lte", 100)),
                name="ticket_urgency_range",
            ),
        ),
    ]
